# Generated by Django 4.2.13 on 2024-08-02 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tiền điện tử',
                'verbose_name_plural': 'Tiền điện tử',
                'db_table': 'crypto_coin',
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='Khóa chính mỗi transaction', primary_key=True, serialize=False, verbose_name='id')),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('sender', models.CharField(max_length=42)),
                ('receiver', models.CharField(max_length=42)),
                ('transaction_type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=15)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Giao dịch',
                'db_table': 'transactions',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='Khóa chính bảng giá tiền điện tử', primary_key=True, serialize=False, verbose_name='id')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.cryptocoin')),
            ],
            options={
                'verbose_name': 'Giá tiền điện tử',
                'verbose_name_plural': 'Giá tiền điện tử',
                'db_table': 'crypto_price',
                'ordering': ('-timestamp',),
            },
        ),
    ]
