# Generated by Django 4.2.13 on 2024-08-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocoin',
            options={'ordering': ('id',), 'verbose_name': 'Tiền điện tử', 'verbose_name_plural': 'Tiền điện tử'},
        ),
        migrations.AddField(
            model_name='cryptocoin',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
