# Generated by Django 4.2.13 on 2024-08-05 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_cryptocoin_options_cryptocoin_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created_at',), 'verbose_name': 'Giao dịch', 'verbose_name_plural': 'Giao dịch'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tx_hash',
        ),
        migrations.AddField(
            model_name='transaction',
            name='blockchain_net',
            field=models.CharField(default='BNB Smart Chain (BEP20)', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.cryptocoin'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='coin_name',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='VND', max_length=7),
        ),
        migrations.AddField(
            model_name='transaction',
            name='guid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price_transfer',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
