# Generated by Django 4.2.13 on 2024-08-05 15:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='Khóa chính mỗi transaction', primary_key=True, serialize=False, verbose_name='id')),
                ('guid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('transaction_type', models.CharField(default='buy', max_length=15)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('coin_name', models.CharField(blank=True, max_length=7, null=True)),
                ('price_transfer', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('currency', models.CharField(default='VND', max_length=7)),
                ('user_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=42, null=True)),
                ('blockchain_net', models.CharField(default='BNB Smart Chain (BEP20)', max_length=255)),
                ('fee', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('remain', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.cryptocoin')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Giao dịch',
                'db_table': 'buy_transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
